services:
  postgres:
    image: postgres:17
    container_name: postgres-outbox-lab
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: asclepio_lab
    ports:
      - "5432:5432"
    volumes:
      - ./docker/init:/docker-entrypoint-initdb.d