services:
  postgres:
    image: postgres:17
    container_name: postgres-outbox-lab
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: asclepio_lab
    ports:
      - "5432:5432"
    volumes:
      - ./docker/init:/docker-entrypoint-initdb.d
  rabbitmq:
    image: rabbitmq:4.3-management-alpine
    container_name: rabbitmq-outbox-lab
    restart: always
    ports:
      # Broker (AMQP)
      - "5672:5672"
      # (Management UI)
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
